<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Brigid.Data\Brigid.Data.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Brigid.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Chaos.DarkAges"/>
        <PackageReference Include="Markdig"/>
        <PackageReference Include="MonoGame.Framework.DesktopGL"/>
        <PackageReference Include="FontStashSharp.MonoGame"/>
    </ItemGroup>
</Project>