<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Chaos.DarkAges"/>
        <PackageReference Include="Chaos.Geometry"/>
        <PackageReference Include="DALib" Condition="'$(UseLocalDALib)' != 'true'" />
        <ProjectReference Include="$(LocalDALibProjectPath)" Condition="'$(UseLocalDALib)' == 'true'" />
        <PackageReference Include="Hybrasyl.Protocol" Condition="'$(UseLocalProtocol)' != 'true'" />
        <ProjectReference Include="$(LocalProtocolProjectPath)" Condition="'$(UseLocalProtocol)' == 'true'" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Brigid.Tests" />
    </ItemGroup>
</Project>