<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Chaos.Common"/>
        <PackageReference Include="Chaos.DarkAges"/>
        <PackageReference Include="Chaos.Geometry"/>
        <ProjectReference Include="..\..\dalib\DALib\DALib.csproj" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory"/>
    </ItemGroup>
</Project>